'use client';

import { SiteNav, SiteFooter } from '@/components/navigation';
import { useI18n } from '@pdf-editor/editor/i18n';

export default function PrivacyPage() {
  const { t } = useI18n();
  return <main className="site-shell"><SiteNav /><header className="site-page-heading"><span className="site-kicker">{t('Your files. Your control.')}</span><h1>{t('Privacy, in plain language.')}</h1><p>{t('Opening, editing and saving your PDF happens on your device.')}</p></header>
    <article className="site-prose">{[
      ['Working with files', 'Your PDF is opened from your computer. Ordinary editing and saving do not upload it to a cloud drive. Passwords are handled on your device.'],
      ['Using AI', 'komo sends a request only when you ask for help. On the web, after your permission, the chosen text, page images and recent conversation are sent to the AI service; the original PDF stays on your device. Web conversations live only in the current tab and are not saved by the app. Desktop tasks may send the materials needed for the requested work. Opening a PDF alone does not start an AI request.'],
      ['Local preferences & recovery', 'We save your language preference and document recovery data on this device. You can manage browser storage in your browser settings. Files generated by the desktop app remain on your computer until you remove them.'],
      ['Accounts & payments', 'We use your account information for sign-in, subscriptions and support. Subscription payments are processed by Stripe.'],
      ['KolmoPDF full-text reading', 'When you use KolmoPDF, your documents are sent to KolmoPDF for parsing. KolmoPDF handles this data under its own privacy policy.'],
      ['No advertising trackers', 'We do not use advertising trackers.'],
    ].map(([title,text]) => <section key={title}><h2>{t(title!)}</h2><p>{t(text!)}</p></section>)}<p>{t('Questions?')} <a href="mailto:security@komopdf.com">security@komopdf.com</a></p></article><SiteFooter /></main>;
}
