'use client';

import { SiteNav, SiteFooter } from '@/components/navigation';
import { useI18n } from '@pdf-editor/editor/i18n';

export default function PrivacyPage() {
  const { t } = useI18n();
  return <main className="site-shell"><SiteNav /><header className="site-page-heading"><span className="site-kicker">{t('Your files. Your control.')}</span><h1>{t('Privacy, in plain language.')}</h1><p>{t('Opening, editing and saving your PDF happens on your device.')}</p></header>
    <article className="site-prose">{[
      ['Working with files', 'Your PDF is opened from your computer. Ordinary editing and saving do not upload it to a cloud drive. Passwords are handled on your device.'],
      ['Using AI', 'The web editor does not currently include an AI assistant. In the desktop app, a request is sent only when you ask komo to do something. The materials needed for that task may be sent to the AI service. Opening a PDF alone does not start an AI request.'],
      ['Local preferences & recovery', 'We save your language preference and document recovery data on this device. You can manage browser storage in your browser settings. Files generated by the desktop app remain on your computer until you remove them.'],
      ['No account required', 'You do not need an account or a subscription to use komopdf. We do not use advertising trackers.'],
    ].map(([title,text]) => <section key={title}><h2>{t(title!)}</h2><p>{t(text!)}</p></section>)}<p>{t('Questions?')} <a href="mailto:security@komopdf.com">security@komopdf.com</a></p></article><SiteFooter /></main>;
}
